imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@WABackendBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    wa.app_url: 'http://www.coopidrogas.com.co'

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            contactosProveedor:
                driver:   pdo_mysql
                host:     192.168.1.31
                port:     "%database_port%"
                dbname:   contactos_proveedor
                user:     ContactosProveedor
                password: '#ContPIdb01*SqLD'
                charset:  UTF8
            proveedores:
                driver:   pdo_mysql
                host:     192.168.1.33
                port:     "%database_port%"
                dbname:   sipproveedores
                user:     Sipproveedores
                password: '#SippPIdb01*SqLD'
                charset:  UTF8
            connections:
                persistent: true

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        #auto_mapping: true
        default_entity_manager:   default
        entity_managers:
            default:
                connection:       default
                mappings:
                    WABackendBundle: ~
            contactosProveedor:
                connection:       contactosProveedor
                mappings:
                    WABackendBundle: ~
            proveedores:
                connection:       proveedores
                mappings:
                    WABackendBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
#    username:  "%mailer_user%"
#    password:  "%mailer_password%"
    spool:     { type: memory }
